name: Update Packages

on:
  repository_dispatch:
    types: [update_packages]

jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: set remote url
      run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: package-update
      uses: taichi/actions-package-update@master
      env:
        AUTHOR_EMAIL: ci@smartcar.com
        AUTHOR_NAME: SmartcarCI      
        EXECUTE: "true"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL: debug
        UPDATE_COMMAND: npm ci
      with:
        args: -u --packageFile package.json --loglevel verbose
